FROM node:20.18.0-slim as builder

WORKDIR /app

COPY package*.json /app

RUN npm install

COPY . /app

RUN npm run build

FROM node:20.18.0-slim

RUN npm install -g serve

COPY --from=builder /app/.output /app/.output

EXPOSE 3000

CMD ["node", "/app/.output/server/index.mjs"]
